apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-nginx-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi